import Lean

register_simp_attr add_pull
register_simp_attr add_push
register_simp_attr sum_push
register_simp_attr sum_pull
register_simp_attr sub_pull
register_simp_attr sub_push
register_simp_attr neg_pull
register_simp_attr neg_push
register_simp_attr smul_pull
register_simp_attr smul_push
register_simp_attr mul_pull
register_simp_attr mul_push

register_simp_attr pow_push
register_simp_attr pow_pull

register_simp_attr exp_push
register_simp_attr exp_pull
register_simp_attr log_push
register_simp_attr log_pull


register_simp_attr simp_core
-- register_simp_attr ftrans_simp
