import SciLean.Core.FunctionPropositions.Differentiable
import SciLean.Core.FunctionPropositions.DifferentiableAt
import SciLean.Core.FunctionPropositions.IsContinuousLinearMap
import SciLean.Core.FunctionPropositions.IsDifferentiable
import SciLean.Core.FunctionPropositions.IsDifferentiableAt
